### ISSUE TITLE
Plugins not found on macOS

### ISSUE THREAD

**Issue by mohd-akram** [audacious-media-player/audacious#1364]
**Describe the bug**
Plugins aren't found on macOS when audacious-plugins is built using autotools due to the plugins being created as `.bundle` directories, rather than files. This causes them to be skipped: https://github.com/audacious-media-player/audacious/blob/0daed5ab491d40fa320c81505fc1c4ed8e9bb930/src/libaudcore/plugin-load.cc#L144

As a side note, it seems #57 updated the configure script but it doesn't use the new `BUILDSYS_PLUGIN` anywhere so `PLUGIN_SUFFIX` isn't set despite being used in the code.

**Steps to reproduce**
`./configure`

**Expected behavior**
Plugins are found

**Additional information**
* Audacious version and interface (Qt / GTK / Winamp): 4.3.1 Qt
* Operating system and version: macOS

**Comment by mohd-akram** [comment]
Note that plugins still won't work on macOS after fixing this issue (via adding `BUILDSYS_PLUGIN` to `configure.ac`). This is because buildsys places the library in a nested directory (`Contents/MacOS`) and so `dlopen` on the `.bundle` fails. I imagine this has been broken since [this commit](https://fossil.nil.im/buildsys/info/f9207c957aa74581) in buildsys. The meson build correctly just uses a simple `.dylib`. I would suggest changing `PLUGIN_SUFFIX` to `.dylib` (ideally it should be `.so` - see mesonbuild/meson#1160), and `LINK_PLUGIN`, `INSTALL_PLUGIN` and `UNINSTALL_PLUGIN` for Darwin to match the other platforms.

**Comment by radioactiveman** [comment]
To make things more clear: Plugins are not loaded because `libaudcore` requires `PLUGIN_SUFFIX` for the loader to be set here:

https://github.com/audacious-media-player/audacious/blob/181215b252aeb11a8c4203ebf5377c3817ad33d0/src/libaudcore/plugin-load.cc#L134-L135

`BUILDSYS_PLUGIN` which initializes `PLUGIN_SUFFIX` is not used in `audacious/configure.ac`, only for audacious-plugins (https://github.com/audacious-media-player/audacious-plugins/commit/cff3718983ae6c073205eb737c0777b3ba98ab5a).

---

@Midar: As buildsys maintainer, could you please give feedback and suggestions on how to fix this? 
I also wonder if this line should still be required now, added years ago with https://github.com/audacious-media-player/audacious/commit/3155f43823ca9a14d6698e8d21a82187d0e37234.
https://github.com/audacious-media-player/audacious/blob/f97494180fbab23730c3c8ac426460a429405127/configure.ac#L27

Thanks.

**Comment by Midar** [comment]
macOS and iOS are a little bit different here. There is a native plugin system that uses bundles (see https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFBundles/AboutBundles/AboutBundles.html and https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFBundles/BundleTypes/BundleTypes.html#//apple_ref/doc/uid/10000123i-CH101-SW32) and buildsys.mk fully supports that. Just using a `.dylib` instead of a proper native plugin has some drawbacks - even worse would be using `.so` because macOS and iOS do not even use ELF, so that would be basically the same as renaming a `.bmp` to `.png` and calling it compressed.

While it would be possible to create a `.dylib` and load that pretending it is just a shared library, this has some serious drawbacks: It would not work properly with codesigning, plugins could not ship their dependencies as frameworks, resources the plugin might depend on are missing and metainfo as is stored in Info.plist would also not be possible.

buildsys.mk fully supports this and (at least in the latest version) handles all these automatically: If an Info.plist is present, it is copied into the .bundle and the .bundle properly signed. It also checks whether an iOS or macOS bundle is being built, as those use a different directory structure.

In order to load such a bundle, you can still `dlopen` it. But instead of `dlopen`ing `myplugin.bundle`, you open `myplugin.bundle/Contents/MacOS/myplugin` on macOS and `myplugin.bundle/myplugin` on iOS. I recommend creating a wrapper around `dlopen` such as here: https://objfw.nil.im/file?ci=trunk&name=src/OFPlugin.m&ln=47-58 This takes a path to the plugin without the suffix and loads it.

This also means the line defining `PLUGIN_SUFFIX` is not gonna cut it and you need to call `BUILDSYS_PLUGIN` for it to properly detect what kind of plugin to build.

**Comment by mohd-akram** [comment]
@radioactiveman I made a correction to the issue. The lack of `PLUGIN_SUFFIX` and missing `BUILDSYS_PLUGIN` is a side issue. Since the suffix is an empty string, that check always passes (which is a separate issue). The actual problem is that a secondary check ignores the bundle because it's a directory (I updated the issue above with details).

@Midar I did not realize you were on GitHub, I sent you an email with a bug report :), and I just saw your response. I think it would be difficult to write cross-platform code via this bundle directory structure as it's very Apple specific. I see there's `CFBundleGetDataPointerForName` which I think can achieve this for the plugins. Regarding `.so`, that's what autotools does and even Apple ships `.so` files (albeit third-party, see the meson issue I linked earlier), and Apple has mentioned the `.bundle` extension as well for that (although IMO that's too confusing). Perhaps you can detect if someone provides an `Info.plist` and only then create that structure, since that's when you get most of the benefit of it.

**Comment by Midar** [comment]
@mohd-akram It's true that it's Apple-specific, but if you want your code to be code signed, which is a requirement for the App Store (and might even be required if the application itself is signed), you have no other way. It's possible to write cross-platform code with it, see `OFPlugin` that I linked to. This abstracts it away for an application that doesn't want to care and Audacious could do the same. It could even use ObjFW and `OFPlugin` for that, but I'm not sure Audacious wants to pull in ObjFW as a dependency ;). (Though it could probably also use some of its other functionalities.)

Creating a Mach-O loadable that is called .bundle at the same path where a directory with a `.bundle` would be expected just sounds like it will create a lot of trouble and a debugging nightmare. Even without an `Info.plist`, you can have a .bundle. It's certainly not ideal or recommended, but it works. I'm not a fan of the presence of a single file in a directory completely changing the behavior in an entirely incompatible way.

Yes, Apple does ship `.so` files with macOS -- with Python, in particular, because Python always got this wrong. However, all .bundle it ships with a directories following the bundle structure. I would be curious to see where Apple documented .bundle as an extension for Mach-O files?

**Comment by mohd-akram** [comment]
I don't know a ton about codesigning, but I feel like you could still sign it via signing the application bundle. I agree that calling it `.bundle` as a file would be confusing, but it seems that build systems have settled on `.so`. There's also the issue that autotools and meson are producing different results for audacious, and that would complicate the code to handle both. Meson can be made to use `.so` via something like [this](https://github.com/p11-glue/p11-kit/commit/8a4348e8468d08d992cb7d22a4d887d0191383f6). As for Apple using it, it's mentioned [here](https://github.com/mesonbuild/meson/issues/1160#issuecomment-1511157623). Note that in your links to Apple's documention it says `Info.plist` is required and "Always include an information-property list (Info.plist) file in your bundle".

I'm not sure about the details of buildsys, but if the auto-detection of `Info.plist` is too magical (I don't think it's **too** bad since you have to be deliberate about creating that plist file), perhaps some flag can be passed, or have it as a separate thing entirely (I think I saw you handle Frameworks completely separately).

**Comment by Midar** [comment]
Codesigning requires it to be a directory. Especially since a .bundle can be outside an .app on macOS. Just because other build systems get it entirely wrong and use `.so` doesn't mean that's the correct thing to do - nor would be calling the Mach-O file `.bundle`. Hence why I asked where Apple documents `.bundle` being an extension for Mach-O files - because it seems they don't. Everything you linked to is 3rd-party software that Apple includes that got it wrong.

You're right in that Info.plist is required to sign the .bundle, but it's still possible to load one without an Info.plist that is unsigned (if loading unsigned plugins is allowed).

Generally, I think "Other build systems got it wrong so buildsys.mk should also be wrong" is not a good argument - especially when how it is now was a direct result of making buildsys.mk produce frameworks and bundles that are compatible with the App Store. If consistency with Meson is a problem, I'm happy to bring it to the Meson people to make sure they get it right as well.

**Comment by Midar** [comment]
After pondering this some more, I suppose we could have both `PLUGIN = foo${PLUGIN_SUFFIX} and `BUNDLE = foo${BUNDLE_SUFFIX}. But it's unclear what PLUGIN_SUFFIX should be - probably the empty string?

**Comment by mohd-akram** [comment]
I don't have too many opinions on this, other than to find a way to make the meson and autoconf builds align. After the discussion in the other thread, I do feel even more now that a bundle without an Info.plist isn't a bundle, so I think my earlier proposed solution of using a simple flat .dylib in the absence of a provided plist file to be simple and configuration-free.

**Comment by Midar** [comment]
You probably want https://fossil.nil.im/buildsys/info/5695217e58e9abf9 which allows you to do both now.

Once Meson supports creating .bundles, Audacious should probably switch to that on macOS.

**Comment by mohd-akram** [comment]
Nice! Now I believe it's just a matter of updating buildsys in Audacious and adding `BUILDSYS_PLUGIN` that I mentioned in the issue.

**Comment by radioactiveman** [comment]
Fixed with https://github.com/audacious-media-player/audacious-plugins/commit/cfb95fa670b9a6d1e7e74820b94cdbe0fbe8daf5 and https://github.com/audacious-media-player/audacious/commit/c9298c7c5d8dce718d0f057091836bd7499ab723.

Thanks @Midar and @mohd-akram. :+1:
