### ISSUE TITLE
Enable Scrobbler plugin for Windows build

### ISSUE THREAD

**Issue by radioactiveman** [audacious-media-player/audacious#1383]
**Description**
With https://github.com/audacious-media-player/audacious-plugins/commit/895e2c3019cc50ec3dd54cd9385c42a35d604f8d the Scrobbler plugin should work on Windows as well.
Can this be enabled for the 4.4 release?

**Side note**
The file name `audacious-4.4-beta1-win32.exe` is confusing if Audacious requires a 64 bit OS now. We should use `win64` instead.

**Comment by jlindgren90** [comment]
I'm undecided on whether to include scrobbler in the Windows builds. Leaning against it since it adds new dependencies (curl and some indirect dependencies - maybe 5-6 more dlls) just to support one 3rd-party service.

Win32 is still used even in Microsoft documentation to refer to the Windows API, even on 64-bit systems.

**Comment by radioactiveman** [comment]
OK, I didn't know the plugin requires so many dependencies. In this case it's fine for me to leave it disabled.

If more users demand it, we can revaluate. Closing as not planned for now.
