### ISSUE TITLE
Add red refugee / ajustement Blue refugee

### ISSUE THREAD

**Issue by Fr-Dae** [audacious-media-player/audacious#1519]
hello, could you make a branch from this issue please ?

and in addition, where are localised the folder `/usr/share/audacious/Skins/Refugee` here ? i do'nt find it 
thanks

**Comment by Fr-Dae** [comment]
@radioactiveman hello

**Comment by radioactiveman** [comment]
The bundled skins are found in the [audacious-plugins](https://github.com/audacious-media-player/audacious-plugins/tree/master/src/skins-data/Skins) repository.

If you want to modify such skin, create a copy and store your version at `~/.local/audacious/Skins/`.

See also: https://github.com/orgs/audacious-media-player/discussions/1489

**Comment by wildstar84** [comment]
I have (created) both a RefugeeRed & RefugeeViolet versions.  If someone can remind me of the properway to zip these up to where Audacious can install them from a compressed file, I'll be happy to bundle 'em up and try to attach it here.

**Comment by Fr-Dae** [comment]
send me your file on discord, i will make a PR to merge all in same time. 
i'm just too busy this week
Dae#5125

**Comment by wildstar84** [comment]
I don't have nor have ever used discord, but here it is as a zip file.  You should be able to download it and just rename it from .zip to .wsz.  I don't remember the details, but I believe Audacious can install additional skins directly from .wsz files if put in a certain directory (~/.audacious/Skins/)?  Otherwise, you could submit a PR with it and perhaps they may merge it as one of their defaults.  If you want, I could do the same for RefugeeViolet.
[RefugeeRed.zip](https://github.com/user-attachments/files/18127984/RefugeeRed.zip)


Regards,

Jim
